### ISSUE TITLE
Human focussed URL scheme

### ISSUE THREAD

**Issue by adamprocter** [adamprocter/nodenogg.in#25]

**Comment by tobymilner** [comment]
# Ideas on URLs

## Definitions
### Microcosms 
* Microcosms are sharable, collaborative space with one or more participants
* You and other participants can add nodes to a microcosm

### Nodes 
* Nodes are the pieces of content that live in the microcosm
* They contain text, images, media and other types of content
* They can be linked to other nodes

## Hosting
* You can host microcosms locally. This means you need to install CouchDB.
* You can also host microcosms on the public nodenogg.in server if you want them to be more easily shareable and persistent.

## URLs
These examples assume a microcosm with the name `example-microcosm` and the unique ID `example-microcosm-0a8892`. The base domain could be either [nodenogg.in](https://nodenogg.in) or [localhost:8080](http://localhost:8080) depending on whether the user is working locally.

### Microcosm
`base-domain/example-microcosm-0a8892`
Microcosm in default canvas/board view

`base-domain/example-microcosm-0a8892/list`
Microcosm in list view

`base-domain/example-microcosm-0a8892/present`
Microcosm in presenter view

### Node
`base-domain/example-microcosm-0a8892/node/098a9-823j10-3788a`
Node in editor/full view mode

We could also reinforce the term microcosm by including it in the URL, e.g.:
`base-domain/microcosm/example-microcosm-0a8892`

## Handling state and local/public microcosms
* If we want users to have both the ability to access local and public microcosms, (e.g. I want to view someone's locally hosted microcosm hosted at their IP at e.g. 109.151.xxx.xx 
 fd26:5316:b449:85dc:xxxx:xxxx:xxxx:xxxx) then I would need to supply both the microcosm unique ID and the hosting IP.
* The URL could be supplied with both elements e.g. `base-domain/109.151.xxx.xx:example-microcosm-0a8892`. In this situation, if the app is accessed through [nodenogg.in](https://nodenogg.in), and no CouchDB domain is provided, it assumes it is the public one [nn.nodenogg.in](https://nn.nodenogg.in).
* The app could retain a history of recent/active microcosms in local storage.
* The URL is the source of truth for the current (active) microcosm.

**Comment by adamprocter** [comment]
this looks great - I wonder is perhaps a user friendly unique id generator could work.. I saw a vue thing that picked from a range of words to generate unique names, but this maybe not worth it.

I also think that perhaps simplification might be to always have the /microcosm in the URL 

base-domain/microcosm/workshop-0x9976

the objectname (clientid) you arrive with could then perhaps be given a unique name the person never sees

```
if (localStorage.getItem('mylastMicrocosm') == null) {
  var microcosm = 'firstvisit'
} else {
  microcosm = localStorage.getItem('mylastMicrocosm')
}

if (localStorage.getItem('myNNClient') == null) {
  myclient = 'firstvisit'
} else {
  myclient = localStorage.getItem('myNNClient')
}
```

**Comment by adamprocter** [comment]
https://en.wikipedia.org/wiki/Clean_URL

**Comment by adamprocter** [comment]
https://router.vuejs.org/guide/essentials/history-mode.html

**Comment by tobymilner** [comment]
So this is based on the idea that you need unique IDs to avoid clashes particularly when using the public CouchDB at [nn.nodenogg.in](https://nn.nodenogg.in).

## Name-based IDs
* If you are asking users to name their microcosms when you create them, you could use a combination of a [slugify-ed](https://github.com/simov/slugify) name and append a random string for uniqueness (e.g. [uuid](https://github.com/uuidjs/uuid)). The reason for using the name as part of the unique ID is to make it friendlier to share and identify in a list.
* One challenge there is that the that if the microcosm name is changed, then the unique ID should probably change as well, as it reflects the name.

## Nicer unique IDs
You could use something like [haikunator](https://github.com/usmanbashir/haikunator).

**Comment by adamprocter** [comment]
var urlparam = this.$route.query.instance
    var urlparam2 = this.$route.query.device

    if (urlparam2 != undefined) {
      this.device = urlparam2
      localStorage.myNNClient = this.device
    }

    if (urlparam != undefined) {
      this.urlinstance = urlparam
      this.$store.dispatch('createInstance', this.urlinstance)
    }

**Comment by adamprocter** [comment]
in App.vue 

   data: function() {
    return {
      urlinstance: '',
      clientid: '',
      device: ''
    }
  },

**Comment by adamprocter** [comment]
Comments are possibly ways this was implemented before to take URL parameter and connect you to the right microcosm
